# Generated by Django for CalculationHistory model
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operand1', models.FloatField(help_text='First operand')),
                ('operand2', models.FloatField(help_text='Second operand')),
                ('operator', models.CharField(max_length=5, help_text='Arithmetic operator (+, -, *, /)')),
                ('result', models.FloatField(help_text='Calculation result')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Calculation timestamp')),
            ],
        ),
    ]
